<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ff4cb345fa25',
	'title' => 'Réseaux sociaux',
	'fields' => array(
		array(
			'key' => 'field_5ff4cd847d4d7',
			'label' => 'Affichage des liens',
			'name' => 'affichage_des_liens',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ff4cb837d4d4',
			'label' => 'Liens',
			'name' => 'liens',
			'type' => 'repeater',
			'instructions' => 'Entrer ici vos liens de réseaux sociaux.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ff4cd847d4d7',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5ff4cc6d7d4d6',
					'label' => 'Réseau',
					'name' => 'reseau',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'choices' => array(
						'Facebook' => 'Facebook',
						'Instagram' => 'Instagram',
						'LinkedIn' => 'LinkedIn',
						'Youtube' => 'Youtube',
						'GitHub' => 'GitHub',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ff4cc477d4d5',
					'label' => 'Lien',
					'name' => 'lien',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'hero-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'show_in_graphql' => 1,
	'graphql_field_name' => 'reseauxSociaux',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1609886612,
));

endif;