backend:
  name: git-gateway #git-gateway ou test-repo
  branch: development
publish_mode: editorial_workflow
locale: 'fr'
media_folder: 'public/images/uploads'
public_folder: '/public/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'date' }
      - { label: "Image mise de l'avant", name: 'thumbnail', widget: 'image' }
      - { label: 'Contenu', name: 'content', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Contenu', name: 'content', widget: 'markdown' }
  - name: 'menus'
    label: 'Menus'
    files:
      - name: 'main'
        label: 'Principal'
        file: 'content/menus/main.yml'
        fields:
          - name: 'item'
            label: 'Élément'
            widget: list
            summary: '{{name}} - {{page}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - {
                  label: 'Page',
                  name: 'page',
                  widget: 'relation',
                  collection: 'pages',
                  search_fields: ['title'],
                  value_field: '{{slug}}',
                  display_fields: ['{{title}}'],
                }
